package com.vk2.touchsreentab.fragment.fragmentcontroller;

public enum Fragmentez {
    PAGE_FRAGMENT,
    PLAYER_FRAGMENT,
    CONTROL_FRAGMENT,
    ARTIST_FRAGMENT,
    PLAYLIST_FRAGMENT,
    RECOMMEND_FRAGMENT,
    SEARCH_COMPLEX_FRAGMENT,
    SEARCH_YOUTUBE_FRAGMENT,
    SINGER_FRAGMENT,
    SONG_FRAGMENT,
    SETTING_FRAGMENT
}