package com.vk2.touchsreentab.fragment.fragmentcontroller;

public enum Fragmentez {
    PAGE_FRAGMENT,
    NORMAL_PLAYER_FRAGMENT,
    EXO_PLAYER_FRAGMENT,
    YOUTUBE_PLAYER_FRAGMENT,
    CONTROL_FRAGMENT,
    ARTIST_FRAGMENT,
    PLAYLIST_FRAGMENT,
    RECOMMEND_FRAGMENT,
    SEARCH_COMPLEX_FRAGMENT,
    SEARCH_YOUTUBE_FRAGMENT,
    SEARCH_SOUNDCLOUND_FRAGMENT,
    SINGER_FRAGMENT,
    SONG_FRAGMENT,
    SETTING_FRAGMENT,
    HISTORY_FRAGMENT,
    DOWNLOAD_FRAGMENT
}